<?php

echo ord('A') . "\n";
echo ord('B') . "\n";
echo ord('Y') . "\n";
echo ord('Z') . "\n";
echo "\n";
echo ord('a') . "\n";
echo ord('b') . "\n";
echo ord('y') . "\n";
echo ord('z') . "\n";
echo "\n";
echo ord('0') . "\n";
echo ord('1') . "\n";
echo ord('8') . "\n";
echo ord('9') . "\n";
echo "\n";
echo ord('!') . "\n";
echo ord('@') . "\n";
echo ord('#') . "\n";
echo ord('$') . "\n";
echo ord('%') . "\n";
echo ord('^') . "\n";
echo ord('*') . "\n";
echo ord('(') . "\n";
echo ord(')') . "\n";
echo ord('-') . "\n";
echo ord('_') . "\n";
echo ord('+') . "\n";
echo ord('=') . "\n";
echo ord('{') . "\n";
echo ord('}') . "\n";
echo ord('[') . "\n";
echo ord(']') . "\n";
